# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kalex/golang/src/Chessify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kalex/golang/src/Chessify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kalex/golang/src/Chessify/CMakeFiles /home/kalex/golang/src/Chessify//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kalex/golang/src/Chessify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chessify

# Build rule for target.
chessify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessify
.PHONY : chessify

# fast build rule for target.
chessify/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/build
.PHONY : chessify/fast

#=============================================================================
# Target rules for targets named chessify_autogen

# Build rule for target.
chessify_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessify_autogen
.PHONY : chessify_autogen

# fast build rule for target.
chessify_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify_autogen.dir/build.make CMakeFiles/chessify_autogen.dir/build
.PHONY : chessify_autogen/fast

Definitions.o: Definitions.cpp.o
.PHONY : Definitions.o

# target to build an object file
Definitions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/Definitions.cpp.o
.PHONY : Definitions.cpp.o

Definitions.i: Definitions.cpp.i
.PHONY : Definitions.i

# target to preprocess a source file
Definitions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/Definitions.cpp.i
.PHONY : Definitions.cpp.i

Definitions.s: Definitions.cpp.s
.PHONY : Definitions.s

# target to generate assembly for a file
Definitions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/Definitions.cpp.s
.PHONY : Definitions.cpp.s

availableactionsfinder.o: availableactionsfinder.cpp.o
.PHONY : availableactionsfinder.o

# target to build an object file
availableactionsfinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/availableactionsfinder.cpp.o
.PHONY : availableactionsfinder.cpp.o

availableactionsfinder.i: availableactionsfinder.cpp.i
.PHONY : availableactionsfinder.i

# target to preprocess a source file
availableactionsfinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/availableactionsfinder.cpp.i
.PHONY : availableactionsfinder.cpp.i

availableactionsfinder.s: availableactionsfinder.cpp.s
.PHONY : availableactionsfinder.s

# target to generate assembly for a file
availableactionsfinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/availableactionsfinder.cpp.s
.PHONY : availableactionsfinder.cpp.s

boardwidget.o: boardwidget.cpp.o
.PHONY : boardwidget.o

# target to build an object file
boardwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/boardwidget.cpp.o
.PHONY : boardwidget.cpp.o

boardwidget.i: boardwidget.cpp.i
.PHONY : boardwidget.i

# target to preprocess a source file
boardwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/boardwidget.cpp.i
.PHONY : boardwidget.cpp.i

boardwidget.s: boardwidget.cpp.s
.PHONY : boardwidget.s

# target to generate assembly for a file
boardwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/boardwidget.cpp.s
.PHONY : boardwidget.cpp.s

chessify_autogen/mocs_compilation.o: chessify_autogen/mocs_compilation.cpp.o
.PHONY : chessify_autogen/mocs_compilation.o

# target to build an object file
chessify_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/chessify_autogen/mocs_compilation.cpp.o
.PHONY : chessify_autogen/mocs_compilation.cpp.o

chessify_autogen/mocs_compilation.i: chessify_autogen/mocs_compilation.cpp.i
.PHONY : chessify_autogen/mocs_compilation.i

# target to preprocess a source file
chessify_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/chessify_autogen/mocs_compilation.cpp.i
.PHONY : chessify_autogen/mocs_compilation.cpp.i

chessify_autogen/mocs_compilation.s: chessify_autogen/mocs_compilation.cpp.s
.PHONY : chessify_autogen/mocs_compilation.s

# target to generate assembly for a file
chessify_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/chessify_autogen/mocs_compilation.cpp.s
.PHONY : chessify_autogen/mocs_compilation.cpp.s

core.o: core.cpp.o
.PHONY : core.o

# target to build an object file
core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/core.cpp.o
.PHONY : core.cpp.o

core.i: core.cpp.i
.PHONY : core.i

# target to preprocess a source file
core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/core.cpp.i
.PHONY : core.cpp.i

core.s: core.cpp.s
.PHONY : core.s

# target to generate assembly for a file
core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/core.cpp.s
.PHONY : core.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessify.dir/build.make CMakeFiles/chessify.dir/player.cpp.s
.PHONY : player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chessify_autogen"
	@echo "... chessify"
	@echo "... Definitions.o"
	@echo "... Definitions.i"
	@echo "... Definitions.s"
	@echo "... availableactionsfinder.o"
	@echo "... availableactionsfinder.i"
	@echo "... availableactionsfinder.s"
	@echo "... boardwidget.o"
	@echo "... boardwidget.i"
	@echo "... boardwidget.s"
	@echo "... chessify_autogen/mocs_compilation.o"
	@echo "... chessify_autogen/mocs_compilation.i"
	@echo "... chessify_autogen/mocs_compilation.s"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

