version: "3"


tasks:
  cmake:
    aliases:
      - cmake
    desc: "CMake project [automoc on]"
    cmds:
      - cd build && cmake ..

  make:
    aliases:
      - make
    desc: "Make project"
    cmds:
      - cd build && make

  clean:
    aliases:
      - clean
    desc: "Cleaning build directory"
    cmds:
      - rm -rf build/*

  build:
    aliases:
      - build
    desc: "Building project"
    cmds:
      - task cmake
      - task make

  run:
    aliases:
      - run
    desc: "Running Chessify"
    cmds:
      - task build
      - ./build/Chessify
